from ghcr.io/erikbergsten/dev-volumes/builder:0.1.0 as build-arm64

run curl -LO https://download.docker.com/linux/static/stable/aarch64/docker-29.8.2.tgz
run tar xvf docker-29.8.2.tgz

from ghcr.io/erikbergsten/dev-volumes/builder:0.1.0 as build-amd64

run curl -LO https://download.docker.com/linux/static/stable/x86_64/docker-29.8.2.tgz
run tar xvf docker-29.8.2.tgz

arg TARGETARCH
from build-${TARGETARCH} as build

from scratch
copy --from=build /build/docker/ /bin/
